config/routes.rb
Cupcake::Application.routes.draw do
  get "pages/Home"
  get "pages/AboutUs"
  get "pages/PrivacyPolicy"
  get "pages/ContactUs"

  resources :customer_cupcakes
  resources :customers

  
  root :to => 'pages#Home'
  match 'pages/aboutus' => 'pages#AboutUs'
  match 'pages/contactus' => 'pages#ContactUs'
  match 'pages/privacypolicy' => 'pages#PrivacyPolicy'  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
attr_accessor :firstName, :lastName, :address, :email, :phone
validates :firstName, :presence => true
validates :lastName, :presence => true
validates :phone, :presence => true
validates :email, :presence => true
validates_format_of :phone, :with => /^(\+?\{11}|\+?\d{3}?[-.]?\d{4}[-.]?\d{4})$/, :message => "should be 11 digits"
#validates_format_of :email, :with => /^[\w]([^@\s,:]+)@(([\w_]+\.)(com|edu|org|net|gov|mil|biz|info))$/i, :message => "is not a valid email adress"
before_save :formate_phone

scope :alphabetical, order('lastName, firstName')


private

def formate_phone
	phone = self.phone.to_s
	#to avoid having nil phone field
	phone.gsub!(/[^0-9]/, "")
	#\ refers to regular expression
	self.phone = phone
end

#begin -- added by asma
def proper_name
	firstName + " " + lastName
end
#end -- added by asma

end

app/models/customer_cupcake.rb
class CustomerCupcake < ActiveRecord::Base
attr_accessor :name, :size, :flavor, :icing, :additional_topping, :customer_id
validates :name, :presence => true
validates :customer_id, :presence => true

belongs_to :customer

validates_inclusion_of :flavor, :in => %[Red Velvet, Chocolate, Vanilla, Strawberry, Pistachio], :message => "is not an option", :allow_nil => true, :allow_blank => true
FLAVORS = [ ['RedVelvet', 'Red Velvet'], ['Chocolate', 'Chocolate'], ['Vanilla', 'Vanilla'], ['Strawberry', 'Strawberry'], ['Pistachio', 'Pistachio'] ]

validates_inclusion_of :icing, :in => %[Cream Cheese, Chocolate, Vanilla, Strawberry, Pistachio], :message => "is not an option", :allow_nil => true, :allow_blank => true
ICINGS = [ ['creamcheese', 'Cream Cheese'], ['Chocolate', 'Chocolate'], ['Vanilla', 'Vanilla'], ['Strawberry', 'Strawberry'], ['Pistachio', 'Pistachio'] ]

scope :alphabetical, order('name')
scope :for_user, lambda{|customer_id| where('id = ?', customer_id)}

#Asma: The below method should not be added as we have no date attribute, the below is taken from the visit model
# scope :latest, lambda{|num| limit(num).order('visit_date DESC')}  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customer_cupcakes_controller.rb
class CustomerCupcakesController < ApplicationController
  # GET /customer_cupcakes
  # GET /customer_cupcakes.json
  def index
    @customer_cupcakes = CustomerCupcake.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customer_cupcakes }
    end
  end

  # GET /customer_cupcakes/1
  # GET /customer_cupcakes/1.json
  def show
    @customer_cupcake = CustomerCupcake.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer_cupcake }
    end
  end

  # GET /customer_cupcakes/new
  # GET /customer_cupcakes/new.json
  def new
    @customer_cupcake = CustomerCupcake.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer_cupcake }
    end
  end

  # GET /customer_cupcakes/1/edit
  def edit
    @customer_cupcake = CustomerCupcake.find(params[:id])
  end

  # POST /customer_cupcakes
  # POST /customer_cupcakes.json
  def create
    @customer_cupcake = CustomerCupcake.new(params[:customer_cupcake])

    respond_to do |format|
      if @customer_cupcake.save
        format.html { redirect_to @customer_cupcake, notice: 'Customer cupcake was successfully created.' }
        format.json { render json: @customer_cupcake, status: :created, location: @customer_cupcake }
      else
        format.html { render action: "new" }
        format.json { render json: @customer_cupcake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customer_cupcakes/1
  # PUT /customer_cupcakes/1.json
  def update
    @customer_cupcake = CustomerCupcake.find(params[:id])

    respond_to do |format|
      if @customer_cupcake.update_attributes(params[:customer_cupcake])
        format.html { redirect_to @customer_cupcake, notice: 'Customer cupcake was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer_cupcake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_cupcakes/1
  # DELETE /customer_cupcakes/1.json
  def destroy
    @customer_cupcake = CustomerCupcake.find(params[:id])
    @customer_cupcake.destroy

    respond_to do |format|
      format.html { redirect_to customer_cupcakes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Home
  end

  def AboutUs
  end

  def PrivacyPolicy
  end

  def ContactUs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customer_cupcakes_helper.rb
module CustomerCupcakesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/customer_cupcakes/_form.html.erb
<%= form_for(@customer_cupcake) do |f| %>
  <% if @customer_cupcake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_cupcake.errors.count, "error") %> prohibited this customer_cupcake from being saved:</h2>

      <ul>
      <% @customer_cupcake.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :flavor %><br />
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :icing %><br />
    <%= f.text_field :icing %>
  </div>
  <div class="field">
    <%= f.label :additional_topping %><br />
    <%= f.text_field :additional_topping %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customer_cupcakes/edit.html.erb
<h1>Editing customer_cupcake</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_cupcake %> |
<%= link_to 'Back', customer_cupcakes_path %>

app/views/customer_cupcakes/index.html.erb
<h1>Listing customer_cupcakes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Size</th>
    <th>Flavor</th>
    <th>Icing</th>
    <th>Additional topping</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customer_cupcakes.each do |customer_cupcake| %>
  <tr>
    <td><%= customer_cupcake.name %></td>
    <td><%= customer_cupcake.size %></td>
    <td><%= customer_cupcake.flavor %></td>
    <td><%= customer_cupcake.icing %></td>
    <td><%= customer_cupcake.additional_topping %></td>
    <td><%= link_to 'Show', customer_cupcake %></td>
    <td><%= link_to 'Edit', edit_customer_cupcake_path(customer_cupcake) %></td>
    <td><%= link_to 'Destroy', customer_cupcake, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer cupcake', new_customer_cupcake_path %>

app/views/customer_cupcakes/new.html.erb
<h1>New customer_cupcake</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_cupcakes_path %>

app/views/customer_cupcakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer_cupcake.name %>
</p>

<p>
  <b>Size:</b>
  <%= @customer_cupcake.size %>
</p>

<p>
  <b>Flavor:</b>
  <%= @customer_cupcake.flavor %>
</p>

<p>
  <b>Icing:</b>
  <%= @customer_cupcake.icing %>
</p>

<p>
  <b>Additional topping:</b>
  <%= @customer_cupcake.additional_topping %>
</p>


<%= link_to 'Edit', edit_customer_cupcake_path(@customer_cupcake) %> |
<%= link_to 'Back', customer_cupcakes_path %>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br />
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br />
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Address</th>
    <th>Email</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.firstName %></td>
    <td><%= customer.lastName %></td>
    <td><%= customer.address %></td>
    <td><%= customer.email %></td>
    <td><%= customer.phone %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @customer.firstName %>
</p>

<p>
  <b>Lastname:</b>
  <%= @customer.lastName %>
</p>

<p>
  <b>Address:</b>
  <%= @customer.address %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @customer.phone %>
</p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cupcake</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/AboutUs.html.erb
<h1>Pages#AboutUs</h1>
<p>Find me in app/views/pages/AboutUs.html.erb</p>

app/views/pages/ContactUs.html.erb
<h1>Pages#ContactUs</h1>
<p>Find me in app/views/pages/ContactUs.html.erb</p>

app/views/pages/Home.html.erb
<h1>Pages#Home</h1>
<p>Find me in app/views/pages/Home.html.erb</p>

app/views/pages/PrivacyPolicy.html.erb
<h1>Pages#PrivacyPolicy</h1>
<p>Find me in app/views/pages/PrivacyPolicy.html.erb</p>